### ISSUE TITLE
There's no file called jtemplatepkg.lpk

### ISSUE THREAD

**Issue by MFernstrom** [silvioprog/jtemplate#9]
The readme says to run jtemplatepkg.lpk, but there's no such file.

**Comment by silvioprog** [comment]
Indeed. The readme needs a small upgrade referencing `jtemplatedt.lpk` instead of `jtemplatepkg.lpk`. Thanks for reporting and feel free to upgrade it (I've fount out the "Collaborators" feature at Github and I've added you and other friends as ones). :-)

**Comment by MFernstrom** [comment]
Thanks!

I've updated the Readme
